from tkinter import *

TITLE = "Test Window"

SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 900

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600 

WINDOW_X = (SCREEN_WIDTH/2) - WINDOW_WIDTH/2
WINDOW_Y = (SCREEN_HEIGHT/2) - WINDOW_HEIGHT/2

FILE_ICON = "icon.png"